# Generated by Django 4.0.2 on 2022-02-06 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0002_customerdetail_ingredient_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ingredient',
            new_name='ingredients',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.customerdetail'),
        ),
    ]
